# permissions for end users to view taskwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: taskwatcher-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operatorkit-task-watcher
    app.kubernetes.io/part-of: operatorkit-task-watcher
    app.kubernetes.io/managed-by: kustomize
  name: taskwatcher-viewer-role
rules:
- apiGroups:
  - batch.operatorkit.github.com
  resources:
  - taskwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.operatorkit.github.com
  resources:
  - taskwatchers/status
  verbs:
  - get
